create dtos about word
e-dialect/hinghwa-dict-backend pull request #150
Opened 2022-07-15 08:49 UTC by lll123github

close #146

2022-07-15 09:13 UTC, FrogDar commented
以后在自己的描述里写上 close #xxx 吧
关闭某个 issue 的意思
比如这个应该是 close #146 ？

2022-07-15 09:13 UTC, lll123github commented
> 以后在自己的描述里写上 close #xxx 吧 关闭某个 issue 的意思 比如这个应该是 close #146 ？

好的，close #146

2022-07-15 09:14 UTC, charlie0129 commented
要写在这个地方 
<img width="600" alt="image" src="https://user-images.githubusercontent.com/55270174/179193379-28b550bd-6358-40d2-915f-4f390d15a0a5.png">

评论里面没用的

2022-07-15 09:15 UTC, lll123github commented
> 要写在这个地方 <img alt="image" width="600" src="https://user-images.githubusercontent.com/55270174/179193379-28b550bd-6358-40d2-915f-4f390d15a0a5.png">
> 
> 评论里面没用的

好的，长知识了，谢谢学长

2022-07-15 09:16 UTC, FrogDar requested changes

2022-07-15 09:16 UTC, FrogDar commented on hinghwa-dict-backend/word/word.py
> +import imp
这个 imp 是啥？（貌似不是第一次出现了？

2022-07-15 09:18 UTC, lll123github commented on hinghwa-dict-backend/word/word.py
> +import imp
！？！？？？？？

2022-07-15 09:20 UTC, FrogDar approved these changes

2022-07-15 09:20 UTC, lll123github commented on hinghwa-dict-backend/word/word.py
> +import imp
那个imp我保不准下一次可能还会出现。
下一次我要仔细看看是咋出现的……

2022-07-15 09:24 UTC, FrogDar commented on hinghwa-dict-backend/word/word.py
> +import imp
https://github.com/e-dialect/hinghwa-dict-backend/pull/150/commits/c1a52a60edb54fa922157a7cbdcaf7ffd6048f18

在这个提交里才有的，反正下次注意吧

2022-07-15 09:26 UTC, lll123github commented
![image](https://user-images.githubusercontent.com/97929788/179195369-6c1a61d2-d26f-4c01-aa44-813678a16abd.png)
#141 也曾经出现过import imp的情况

2022-07-15 09:27 UTC, FrogDar requested changes
有一些莫名奇妙的引用？

2022-07-15 09:27 UTC, FrogDar commented on hinghwa-dict-backend/word/dto/word_all.py
> +from urllib import response
这两个引用干嘛用的？

2022-07-15 09:27 UTC, FrogDar commented on hinghwa-dict-backend/word/dto/word_normal.py
> +from urllib import response
这个引用干嘛用的？

2022-07-15 09:27 UTC, FrogDar commented on hinghwa-dict-backend/word/dto/word_quick.py
> +from urllib import response
这个引用干嘛用的

2022-07-15 09:27 UTC, FrogDar commented on hinghwa-dict-backend/word/dto/word_simple.py
> +from urllib import response
这个引用干嘛用的

2022-07-15 09:28 UTC, lll123github commented on hinghwa-dict-backend/word/dto/word_simple.py
> +from urllib import response
我也是很奇怪。在black之后就加上了？

2022-07-15 09:29 UTC, lll123github commented on hinghwa-dict-backend/word/dto/word_simple.py
> +from urllib import response
> 有一些莫名奇妙的引用？

在上一次的music_normal中也出现了类似的情况

2022-07-15 09:31 UTC, lll123github commented on hinghwa-dict-backend/word/dto/word_simple.py
> +from urllib import response
![image](https://user-images.githubusercontent.com/97929788/179196164-e91fb9e0-0997-47fb-ac2d-0c865e084415.png)
例如这个，前两行也是莫名其妙加上的，在格式化的时候

2022-07-15 09:39 UTC, FrogDar commented on hinghwa-dict-backend/word/dto/word_simple.py
> +from urllib import response
你用什么格式化的？我使用了 black 进行测试，并没有复现你说的情况。

2022-07-15 09:39 UTC, FrogDar approved these changes

2022-07-15 09:40 UTC, FrogDar commented on hinghwa-dict-backend/word/dto/word_normal.py
> +    }
创建这个对象之后 是不是应该 

```python
return response
```

呢？

2022-07-15 09:41 UTC, lin594 commented on hinghwa-dict-backend/word/dto/word_simple.py
> +    }
创建这个对象之后 是不是应该 

```python
return response
```

呢？

2022-07-15 09:42 UTC, lll123github commented on hinghwa-dict-backend/word/dto/word_normal.py
> +    }
嗯对的

2022-07-15 09:42 UTC, lll123github commented on hinghwa-dict-backend/word/dto/word_simple.py
> +    }
对

2022-07-15 09:49 UTC, FrogDar approved these changes

2022-07-15 09:54 UTC, FrogDar requested changes
WD0202 接口，这里面是不是有一个 word_simple ？ 
![image](https://user-images.githubusercontent.com/20886330/179200198-63f8e8c0-9b14-42a5-8f3c-c03536fd9c4c.png)

2022-07-15 09:57 UTC, FrogDar commented on hinghwa-dict-backend/word/word.py
>  from .models import Word, Pronunciation, User, Application
另外，由于 word2pronunciation 函数已经单独提取到一个文件里了，因此这里可以不 import Pronunciation了

2022-07-15 09:59 UTC, FrogDar commented on hinghwa-dict-backend/word/dto/word_simple.py
> +from ..models import Word, User
这里的 User 也没用用到

2022-07-15 09:59 UTC, lll123github commented
> WD0202 接口，这里面是不是有一个 word_simple ？ ![image](https://user-images.githubusercontent.com/20886330/179200198-63f8e8c0-9b14-42a5-8f3c-c03536fd9c4c.png)

对，我没看到。我改一下

2022-07-15 10:00 UTC, lll123github commented on hinghwa-dict-backend/word/dto/word_simple.py
> +from ..models import Word, User
好的

2022-07-15 10:06 UTC, lll123github commented on hinghwa-dict-backend/word/word.py
>  from .models import Word, Pronunciation, User, Application
好的

2022-07-15 10:06 UTC, FrogDar approved these changes

2022-07-15 10:09 UTC, FrogDar approved these changes

2022-07-15 10:11 UTC, FrogDar approved these changes

2022-07-15 10:11 UTC, FrogDar commented
辛苦了

2022-07-15 10:12 UTC, merged

2022-07-15 10:12 UTC, lll123github commented
> 辛苦了

没事，还是缺乏经验

2022-07-15 15:57 UTC, lll123github commented
> 有一些莫名奇妙的引用？

![image](https://user-images.githubusercontent.com/97929788/179261161-f5ffb532-641c-4e68-a8f2-c1e6ef701bc3.png)
![image](https://user-images.githubusercontent.com/97929788/179261210-6ffe070b-3fa4-4982-82b2-26c8570fa4dc.png)
找到原因了

2022-07-15 16:00 UTC, lll123github commented
> 有一些莫名奇妙的引用？

![image](https://user-images.githubusercontent.com/97929788/179261762-ad985be8-fcf4-4926-acf1-4fd12402465c.png)
这个是发生import imp的原因

2022-07-24 13:12 UTC, FrogDar commented on hinghwa-dict-backend/word/dto/word_simple.py
> +    user = Word.contributor
这里应该是 `word` 而不是 `Word` 当时没有审出来

2022-07-24 13:28 UTC, FrogDar commented on hinghwa-dict-backend/word/dto/word_simple.py
> +    user = Word.contributor
fix in #166