check the password valid or not
e-dialect/hinghwa-dict-backend pull request #173
Opened 2022-08-04 17:24 UTC by lll123github

暂未测试，暂时不合并

2022-08-04 17:44 UTC, FrogDar commented on hinghwa-dict-backend/user/password_validation.py
> +        return e
你这个是什么意思嘞？
抛出来的异常的类型显然是 ValidationError 不是你想想的 InvalidPassword 吧？
（是不是没有理解try except的逻辑？）

2022-08-04 17:46 UTC, lll123github commented on hinghwa-dict-backend/user/password_validation.py
> +        return e
我的想法大概是因为按照在issue中讨论的第一张图片说的原本的django自己使用的限制最小使用的是ValidationError，所以限制最大也一样的写，然后上一层的时候统一一下错误类型出一个400

2022-08-04 17:47 UTC, FrogDar commented on hinghwa-dict-backend/user/password_validation.py
> +        return e
但是你的代码并没有实现你说的这种功能

2022-08-04 17:48 UTC, lll123github commented on hinghwa-dict-backend/user/password_validation.py
> +        return e
我看一下try和except的逻辑

2022-08-04 17:48 UTC, charlie0129 commented on hinghwa-dict-backend/utils/exception/types/bad_request.py
> +    def __init__(self, msg="密码不符合规范异常"):
```suggestion
    def __init__(self, msg="密码不符合规范"):
```

2022-08-04 17:48 UTC, FrogDar commented on hinghwa-dict-backend/user/password_validation.py
> +        return e
应该是 except ValidationError as e 然后 raise 一个 InvalidPassword 的异常

2022-08-04 17:49 UTC, FrogDar commented on hinghwa-dict-backend/user/password_validation.py
> +        return e
其他的注释 # 400 并不是说 抓到的就是400 ，只是刚好在lz写的那个代码的那个地方是400而已

2022-08-04 17:50 UTC, lll123github commented on hinghwa-dict-backend/user/password_validation.py
> +        return e
好的，我改一下

2022-08-04 17:52 UTC, FrogDar commented on hinghwa-dict-backend/user/password_validation.py
> +        return e
> 其他的注释 # 400 并不是说 抓到的就是400 ，只是刚好在lz写的那个代码的那个地方是400而已

哦不对，应该说 在那个地方遇到的错误，（之后）都是400类型，实际上做的也是 捕获异常 然后raise一个400

2022-08-04 17:54 UTC, FrogDar requested changes
除了上述需要修改的点外，你还应该为这个部分添加相关自动化测试
（如果不会的话，可以让@Norton-Lin 教一下你 ）

2022-08-04 17:55 UTC, lll123github commented
好的我问一下lz

2022-08-04 17:56 UTC, lll123github commented
另外想问一下token的问题似乎还是没有解决，测试的时候还是会报401不知道为什么

2022-08-04 17:59 UTC, lll123github commented
对，就是你现在看的362行

2022-08-04 18:01 UTC, lll123github commented
我知道为啥了

2022-08-04 18:02 UTC, lll123github commented
我用了测试环境而不是本地Mock

2022-08-04 18:02 UTC, FrogDar requested changes
直接把这个 updatePassword 用类的方法 重构一下

2022-08-04 18:03 UTC, lll123github commented
嗷那我搞错了

2022-08-04 18:03 UTC, lll123github commented
OKKK

2022-08-04 18:06 UTC, FrogDar commented
> 另外想问一下token的问题似乎还是没有解决，测试的时候还是会报401不知道为什么

你是不是密码已经改掉了，所以导致后面再去修改的时候是401？

2022-08-04 18:07 UTC, FrogDar commented
if else 重重叠叠 这个函数赶紧重构得了x
（当然测试得安排上）

2022-08-04 18:07 UTC, lll123github commented
> > 另外想问一下token的问题似乎还是没有解决，测试的时候还是会报401不知道为什么
> 
> 你是不是密码已经改掉了，所以导致后面再去修改的时候是401？

但是我登录没问题来着

2022-08-04 18:08 UTC, lll123github commented
现测试的问题是cs的密码是cs，更改之后由于限制没有办法改成原来的了

2022-08-04 18:09 UTC, lin594 commented
> 现测试的问题是cs的密码是cs，更改之后由于限制没有办法改成原来的了

对呀 那就换一个符合要求的密码去改呀

2022-08-04 18:09 UTC, lll123github commented
那就可能需要在群里重新发一个数据库

2022-08-04 18:10 UTC, FrogDar commented
> 那就可能需要在群里重新发一个数据库

你限制了修改密码，难道还会让原本不符合密码强度的人无法登录？
如果会，那么你的代码就是重大事故，禁止用这种方法
如果不会，那为什么需要重新发一个数据库？

2022-08-04 18:14 UTC, FrogDar commented
> 

自动化测试里面，本身就是新创建的数据库（在CI里面）和你群文件下载的那一份数据库毫无关系

2022-08-04 18:14 UTC, lll123github commented
> > 
> 
> 自动化测试里面，本身就是新创建的数据库（在CI里面）和你群文件下载的那一份数据库毫无关系

OKk

2022-08-04 18:14 UTC, FrogDar commented
> > 
> 
> 自动化测试里面，本身就是新创建的数据库（在CI里面）和你群文件下载的那一份数据库毫无关系

数据库里目前只有两个人 一个叫 admin 一个叫 admin2
![image](https://user-images.githubusercontent.com/20886330/182921743-3ed12e58-daf1-4207-9645-8d7eed7516e8.png)

2022-08-04 18:18 UTC, FrogDar commented
> > 
> 
> 自动化测试里面，本身就是新创建的数据库（在CI里面）和你群文件下载的那一份数据库毫无关系

所以你随便测试随便改都无所谓（当然同一份CI里面用户还是同一个的）
你甚至可以考虑单独创建一个用户专门就是用来测试

2022-08-04 18:18 UTC, lll123github commented
> > > 
> > 
> > 
> > 自动化测试里面，本身就是新创建的数据库（在CI里面）和你群文件下载的那一份数据库毫无关系
> 
> 所以你随便测试随便改都无所谓（当然同一份CI里面用户还是同一个的） 你甚至可以考虑单独创建一个用户专门就是用来测试

好欸

2022-08-04 18:19 UTC, FrogDar commented
> 除了上述需要修改的点外，你还应该为这个部分添加相关自动化测试 （如果不会的话，可以让@Norton-Lin 教一下你 ）

测试至少应该包括：
自己修改：合法情况（新登陆一下看一下能否成功）/太短的情况/太长的情况/旧密码错误导致不让修改的情况
还应该包括：能不能用别人的号来修改你的密码 等

2022-08-04 18:20 UTC, lll123github commented
> 

使用别人的号的意思大概是什么呢

2022-08-04 18:21 UTC, FrogDar commented
> > 
> 
> 使用别人的号的意思大概是什么呢

比如 用户2 去修改了 用户3 的密码，哪怕知道了他的旧密码，这也是不被允许的

2022-08-04 18:21 UTC, lll123github commented
> > > 
> > 
> > 
> > 使用别人的号的意思大概是什么呢
> 
> 比如 用户2 去修改了 用户3 的密码，哪怕知道了他的旧密码，这也是不被允许的

好的

2022-08-06 16:26 UTC, lll123github commented
暂时还没有在测试环境进行测试，也暂时没有添加测试用例

2022-08-06 17:15 UTC, FrogDar commented
> 暂时还没有在测试环境进行测试，也暂时没有添加测试用例

等你准备好了，群里at我吧

2022-08-08 08:40 UTC, FrogDar requested changes

2022-08-08 08:40 UTC, FrogDar commented on hinghwa-dict-backend/utils/exception/types/unauthorized.py
> +    (旧）密码错误
密码错误就行

2022-08-08 08:40 UTC, FrogDar commented on hinghwa-dict-backend/user/views.py
> +from genericpath import exists
这个是无效引用吧？

2022-08-08 08:40 UTC, FrogDar commented on hinghwa-dict-backend/user/views.py
> +from signal import raise_signal
这个是无效引用？

2022-08-08 08:40 UTC, FrogDar commented on hinghwa-dict-backend/user/views.py
> +        token_pass(token, id)  # 401 403
鉴权混乱 改改

2022-08-08 13:22 UTC, lll123github commented
收到，没改完

2022-08-11 13:22 UTC, FrogDar reviewed
代码部分基本小小修改一下就行了，测试快快安排上……（怎么都没什么进度的）

2022-08-11 13:22 UTC, FrogDar commented on hinghwa-dict-backend/user/password_validation.py
> +
既然没有用到这个了，不如删掉？

2022-08-11 13:22 UTC, FrogDar commented on hinghwa-dict-backend/user/password_validation.py
> +
然后把这个文件换个位置吧？放在 `/user/utils/password_validation.py`

2022-08-11 13:22 UTC, FrogDar commented on hinghwa-dict-backend/utils/exception/types/bad_request.py
> +    def __init__(self, msg="密码不符合规范异常"):
@lll123github 这里可以直接 commit 一下

2022-08-11 14:37 UTC, lll123github commented
正在做，这两天确实水了，但是似乎有了新bug？

2022-08-11 14:38 UTC, lll123github commented
好的我测试完之后更改一下文件位置

2022-08-11 15:03 UTC, FrogDar commented on hinghwa-dict-backend/user/password_validation.py
> +    if len(password) < 6 and len(password) > 32:
基本逻辑就错了吧

2022-08-14 09:50 UTC, FrogDar requested changes

2022-08-14 09:50 UTC, FrogDar commented on .github/workflows/e2e.yml
> +          echo -e "from django.contrib.auth.models import User\nuser=User.objects.create_user('user_test_old_password','user_test_old_password@user_test_old_password.com','12')\nuser.save()\nexit()"|
```suggestion
          echo -e "from django.contrib.auth.models import User\nuser=User.objects.create_user('user_test_old_password','user_test_old_password@user_test_old_password.com','12')\nuser.set_password('12')user.save()\nexit()"|python manage.py shell
```

2022-08-14 09:50 UTC, FrogDar commented on .github/workflows/e2e.yml
> +          echo -e "from django.contrib.auth.models import User\nuser=User.objects.create_user('user_test_old_password','user_test_old_password@user_test_old_password.com','12')\nuser.save()\nexit()"|
在底下 `curl 127.0.0.1:8000/users/2` 后面 添加一下 `curl curl 127.0.0.1:8000/users/3` `curl 127.0.0.1:8000/users/4`

2022-08-14 09:50 UTC, FrogDar commented on .github/workflows/e2e.yml
> +          echo -e "from django.contrib.auth.models import User\nuser=User.objects.create_user('user_test_old_password','user_test_old_password@user_test_old_password.com','12')\nuser.save()\nexit()"|
然后你的 `user_test_old_password` 对应的应该是4号用户

2022-08-14 10:30 UTC, lll123github commented on .github/workflows/e2e.yml
> +          echo -e "from django.contrib.auth.models import User\nuser=User.objects.create_user('user_test_old_password','user_test_old_password@user_test_old_password.com','12')\nuser.save()\nexit()"|
OK

2022-08-14 10:54 UTC, lll123github commented on .github/workflows/e2e.yml
> +          echo -e "from django.contrib.auth.models import User\nuser=User.objects.create_user('user_test_old_password','user_test_old_password@user_test_old_password.com','12')\nuser.save()\nexit()"|
> 在底下 `curl 127.0.0.1:8000/users/2` 后面 添加一下 `curl curl 127.0.0.1:8000/users/3` `curl 127.0.0.1:8000/users/4`

我再确认一下 前面的那段代码是有两个curl是么

2022-08-14 16:18 UTC, FrogDar commented
你的 Apifox 里的登录就是有问题的吧？ 怎么没有后置操作？

![image](https://user-images.githubusercontent.com/20886330/184545765-a6ec1080-45f5-447d-ac6d-0e59097a0eaf.png)


没有后置操作的话，别人怎么知道你登录了呢？（登录的依据是 token 你都没更新呀？）
你可以参考一些别人写的能用的登录的接口：
![image](https://user-images.githubusercontent.com/20886330/184545802-e2668e57-8bbb-4821-ab7b-de68c6fb8bf1.png)

2022-08-15 04:24 UTC, lll123github commented
好的，我更改一下

2022-08-19 12:51 UTC, lll123github commented
之后还要加入一部分测试，在新用户注册的密码限制和忘记密码的，看看是先合并另外开issue 还是继续加测试

2022-08-26 11:57 UTC, FrogDar commented
> 限制和忘记密码的，看看是先合并另外开issue 还是继续加测试

这两个因为我们的测试环境里面暂时不支持邮箱验证码的读取，应该是做不到的

2022-08-26 11:57 UTC, FrogDar commented
> > 限制和忘记密码的，看看是先合并另外开issue 还是继续加测试
> 
> 这两个因为我们的测试环境里面暂时不支持邮箱验证码的读取，应该是暂时做不到的，你可以丢一个issue 未来可期x

2022-08-26 11:58 UTC, FrogDar approved these changes

2022-08-26 11:58 UTC, merged