refactor: refactor music module
e-dialect/hinghwa-dict-backend pull request #177
Opened 2022-08-14 06:59 UTC by Norton-Lin

close #176

2022-08-14 09:43 UTC, FrogDar requested changes
先不看了，后续估计一大堆类似的问题：
- 奇怪的包裹 “CommonException” 为何要使用？ 500 的话他会自动抓取的
- 需要先判定权限再开始进行后续操作

2022-08-14 09:43 UTC, FrogDar commented on hinghwa-dict-backend/music/views.py
> +            raise e
包这一层干啥？

2022-08-14 09:43 UTC, FrogDar commented on hinghwa-dict-backend/music/views.py
> +            token = token_pass(request.headers, music.contributor.id)
先判定权限再开始后续操作

2022-08-14 09:43 UTC, FrogDar commented on hinghwa-dict-backend/music/views.py
> +            user = token_user(token)
先判定权限  默认通过的 0 我记得可以不写

2022-08-14 13:44 UTC, Norton-Lin commented on hinghwa-dict-backend/music/views.py
> +            raise e
焯，quiz那块我也这么写的

2022-08-14 16:25 UTC, FrogDar commented on hinghwa-dict-backend/music/views.py
> +            raise e
> 焯，quiz那块我也这么写的

要不然我眼睛瞎了，要不然就是还是有点区别的

2022-08-14 16:26 UTC, FrogDar commented on hinghwa-dict-backend/music/views.py
> +            raise e
不是啊 这个留在干嘛 直接去掉就好了呀？ try except 都丢掉了

2022-08-16 14:40 UTC, FrogDar commented
Any problem?

2022-08-17 04:40 UTC, FrogDar commented on hinghwa-dict-backend/music/views.py
> +        token = token_pass(request.headers, music.contributor.id)
有权限管理的一定要先坚定权限

2022-08-17 04:40 UTC, FrogDar commented on hinghwa-dict-backend/music/views.py
> +        token = token_pass(request.headers, music.contributor.id)
很多地方都是

2022-08-17 08:13 UTC, FrogDar approved these changes

2022-08-17 08:13 UTC, merged