refactor: refactor article module
e-dialect/hinghwa-dict-backend pull request #181
Opened 2022-09-24 03:38 UTC by Norton-Lin

2022-09-24 07:49 UTC, FrogDar requested changes
已经重构过的代码，旧的部分不直接删掉么？

2022-09-24 07:49 UTC, FrogDar commented on hinghwa-dict-backend/article/views.py
> +        return JsonResponse({"comments": comments}, status=200)
那些旧的东西咋没有直接对应的直接删掉呢？

2022-09-24 07:49 UTC, FrogDar commented on hinghwa-dict-backend/utils/TokenCheking.py
> +    if not (info["username"] or info["id"]):
info里面有没有这个字段 可能不能这么写

2022-09-24 07:49 UTC, FrogDar commented on hinghwa-dict-backend/utils/TokenCheking.py
> +    if not ("id" in info or "exp" in info or "username" in info):
这个为啥要改 我没有太过理解.jpg

2022-09-24 07:51 UTC, Norton-Lin commented on hinghwa-dict-backend/article/views.py
> +        return JsonResponse({"comments": comments}, status=200)
淦，忘了删了

2022-09-24 07:52 UTC, Norton-Lin commented on hinghwa-dict-backend/utils/TokenCheking.py
> +    if not (info["username"] or info["id"]):
ok

2022-09-24 08:43 UTC, FrogDar commented
你怎么把原本的对 token 的修改又改了  现在的话没有修复之前的bug把？

2022-09-24 08:45 UTC, Norton-Lin commented
Forbidden那个我不是没改么

2022-09-24 08:56 UTC, FrogDar commented
我感觉42 43 需要改掉吧？要不然走不到下面去
![image](https://user-images.githubusercontent.com/20886330/192089480-a3ab7daa-fd7a-4b3a-8672-04c84bfa5286.png)

2022-09-24 08:58 UTC, Norton-Lin commented
对吼，忘了这茬，那得先判断一下info里面有没有这俩玩意

2022-09-24 09:03 UTC, Norton-Lin commented
但又有个问题，36 37不是判断他俩存在了么

2022-09-24 09:04 UTC, FrogDar commented
那你可以合并一波吧 反正我感觉需要调整一下 现有的代码应该是有问题的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "e-dialect/hinghwa-dict-backend"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月24日(星期六) 下午5:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [e-dialect/hinghwa-dict-backend] refactor: refactor article module (PR #181)





 
但又有个问题，36 37不是判断他俩存在了么
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;

2022-09-24 09:08 UTC, Norton-Lin commented
32-33的这段
` if not ("id" in info and "exp" in info and "username" in info):
        raise InvalidTokenException()`
代码已经可以实现判断存在性了吧，要合并的话 42-43就可以噶了2333

2022-10-02 13:55 UTC, FrogDar approved these changes

2022-10-02 13:55 UTC, merged