feat: add admin review the quiz
e-dialect/hinghwa-dict-backend pull request #185
Opened 2022-10-15 06:30 UTC by Norton-Lin

2022-10-15 09:44 UTC, FrogDar commented on hinghwa-dict-backend/quiz/views.py
> +            msg = body["reason"]
如果没有msg你有做啥特殊处理？

2022-10-15 09:45 UTC, FrogDar commented on hinghwa-dict-backend/quiz/views.py
> +                raise QuizNotFoundException()
其实这种最好是加一个参数，比如表现具体哪一篇quiz不存在的id号这样的）当然不改也可以，没差别

2022-10-15 09:46 UTC, FrogDar requested changes
特殊情况多处理一下就行
然后测试用例的格式化，最好统一一下

2022-10-15 10:56 UTC, Norton-Lin commented on hinghwa-dict-backend/quiz/views.py
> +            msg = body["reason"]
那这不就是无理由驳回了么
不过理论上这个content得发给出题人，但是现在quiz默认管理员添加无出题人

2022-10-15 10:57 UTC, Norton-Lin commented
json文件不是统一扔进vscode去格式化么

2022-10-15 10:57 UTC, Norton-Lin commented on hinghwa-dict-backend/quiz/views.py
> +                raise QuizNotFoundException()
行

2022-10-15 10:58 UTC, Norton-Lin commented on hinghwa-dict-backend/quiz/views.py
> +                raise QuizNotFoundException()
但是不可见的quiz和不存在的quiz,对于用户来说不都是不存在的么

2022-10-17 06:50 UTC, FrogDar commented
> json文件不是统一扔进vscode去格式化么

对吧  不过 vscode 格式化出来的东西可能也有很多种

2022-10-17 06:53 UTC, charlie0129 commented
> > json文件不是统一扔进vscode去格式化么
> 
> 对吧 不过 vscode 格式化出来的东西可能也有很多种

或者搞个统一个格式化工具吧，比如 `jq` ，然后放在 CI 里面检查

就这么搞 `cat text.json | jq > formatted.json`

2022-10-17 06:54 UTC, FrogDar commented
那你搞搞的，我垃圾搞不动的）
看起来挺有意思的事情




开心小蛙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "e-dialect/hinghwa-dict-backend"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月17日(星期一) 下午2:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [e-dialect/hinghwa-dict-backend] feat: add admin review the quiz (PR #185)





   
json文件不是统一扔进vscode去格式化么
  
对吧 不过 vscode 格式化出来的东西可能也有很多种
  
或者搞个统一个格式化工具吧，比如 jq ，然后放在 CI 里面检查
 
就这么搞 cat text.json | jq &gt; formatted.json
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;

2022-11-06 09:04 UTC, FrogDar commented
把添加 CI 的功能先单独分到 #186 
这里就先合并了

2022-11-06 09:04 UTC, FrogDar approved these changes

2022-11-06 09:05 UTC, merged