feat(pronunciation): add ranking in pronunciation uploading
e-dialect/hinghwa-dict-backend pull request #238
Opened 2023-01-13 10:12 UTC by lll123github

feat(pronunciation): add ranking in pronunciation uploading
close #208

2023-01-13 11:40 UTC, lll123github commented
呃好像自动化测试寄了

2023-01-13 11:40 UTC, lll123github commented
如何让它重新跑一遍呢

2023-01-13 11:45 UTC, FrogDar commented
已经开始重新跑了，但我估计还是不行  是 azure 那边的问题

2023-01-13 11:46 UTC, FrogDar commented
https://github.com/FrogDar/code-contributing-practice/issues/5 下次注意清理分支

2023-01-13 12:14 UTC, FrogDar requested changes

2023-01-13 12:14 UTC, lin594 commented on hinghwa-dict-backend/word/models.py
> +    )
不是说给他填充默认值嘛
如果没有默认值的话，返回 pronunciation 的时候你是不是应当处理一下？

2023-01-13 12:14 UTC, FrogDar commented on hinghwa-dict-backend/word/pronunciation/views.py
> +        )  # 这是一个列表，列表的每一个元素是一个元组，每一个元组的第一个元素是用户id。第二个元素是规定时间内贡献次数
https://docs.djangoproject.com/en/3.1/ref/models/querysets/#annotate
用 `django` 自带 `annotate` 来实现吧

2023-01-13 13:03 UTC, lll123github commented on hinghwa-dict-backend/word/models.py
> +    )
![image](https://user-images.githubusercontent.com/97929788/212326279-9c2854d6-0714-480d-8a13-ae4d267d17e2.png)
还是处理了的（应当说是绕开了这个问题）

2023-01-13 13:06 UTC, FrogDar commented on hinghwa-dict-backend/word/models.py
> +    )
行

2023-01-13 15:34 UTC, FrogDar requested changes

2023-01-13 15:34 UTC, FrogDar commented on hinghwa-dict-backend/HinghwaDict/settings.py
> +    },
这个也改成内存 名字的话就叫 `default_cache_table`

2023-01-13 15:34 UTC, FrogDar commented on hinghwa-dict-backend/word/pronunciation/views.py
> +                    except Exception:
如果 `body` 里没有 `word` 字段的话，你这个返回的是什么？   哦 看到了 #240 那就之后解决

2023-01-13 15:34 UTC, FrogDar commented on hinghwa-dict-backend/word/pronunciation/views.py
> +        )
你把这个拼在一起吧
就是直接在 if 里就算出 test_rank 
节省一些查询的资源

2023-01-13 19:01 UTC, FrogDar commented on hinghwa-dict-backend/HinghwaDict/settings.py
> +    },
```suggestion
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "default_cache_table",
    },
```

2023-01-13 19:01 UTC, FrogDar commented on hinghwa-dict-backend/word/pronunciation/views.py
> +        return cache_ranking_table_format  # 返回的是一个列表
```suggestion
    @classmethod
    def update_rank(cls, search_days):  # 不包括存储在数据库中
        if search_days != 0:
            start_date = timezone.now() - datetime.timedelta(days=search_days)
            # 查询上传时间不是空的并且上传时间在规定开始时间之后的
            result = (
                Pronunciation.objects.filter(
                    Q(upload_time__isnull=False) & Q(upload_time__gt=start_date)
                )
                .values("contributor_id")
                .annotate(pronunciation_count=Count("contributor_id"))
                .order_by("-pronunciation_count")
            )
        else:
            result = (
                Pronunciation.objects.values("contributor_id")
                .annotate(pronunciation_count=Count("contributor_id"))
                .order_by("-pronunciation_count")
            )
        resultJSONList = []

        for res in result:
            resultJSONList.append(
                {
                    "contributor": user_simple(
                        User.objects.filter(id=res["contributor_id"])[0]
                    ),
                    "amount": res["pronunciation_count"],
                }
            )
        return resultJSONList  # 返回的是一个列表
```

2023-01-13 19:05 UTC, FrogDar approved these changes

2023-01-13 19:06 UTC, merged

2023-01-14 04:51 UTC, lll123github commented
抱歉昨晚没看到