feat: add tools of quiz voice upload
e-dialect/hinghwa-dict-backend pull request #291
Opened 2023-03-15 07:16 UTC by Norton-Lin

新增测试题语言上传工具

2023-03-15 07:23 UTC, FrogDar requested changes

2023-03-15 07:23 UTC, FrogDar commented on tools/README.md
> +#   小工具集合
后面写点小介绍呀  比如xxx 工具

2023-03-15 07:23 UTC, FrogDar commented on tools/quiz_voice_upload/quiz_voice_upload.py
> +import json
在这个文件夹外面添加一个 readme 吧  怎么使用的 干啥的 都说一下呗

2023-03-15 07:23 UTC, FrogDar commented on tools/quiz_voice_upload/quiz_voice_upload.py
> +env = Env()
这个env是干啥的 我一点都没有理解？

2023-03-15 07:23 UTC, FrogDar commented on tools/quiz_voice_upload/quiz_voice_upload.py
> +    f"https://api.pxm.edialect.top/login", data=json.dumps(data)
网址无论正式服务器还是测试服务器  都应该用一个变量 类似于 `base_url` 这样的方式去组合

2023-03-15 07:23 UTC, FrogDar commented on tools/quiz_voice_upload/quiz_voice_upload.py
> +file = os.listdir(url)
既然是文件夹里的东西 那应该是 `files` 吧？

2023-03-15 07:23 UTC, FrogDar commented on tools/quiz_voice_upload/quiz_voice_upload.py
> +            data=json.dumps(result),
dumps 是啥 挺好奇的

2023-03-15 07:23 UTC, FrogDar commented on tools/quiz_voice_upload/quiz_voice_upload.py
> +        #   res = requests.get(f"http://127.0.0.1:8000/quizzes/{id}", headers={'token': token}).json()
用了 base url  这些注释都没用了吧x

2023-03-15 07:25 UTC, Norton-Lin commented on tools/quiz_voice_upload/quiz_voice_upload.py
> +env = Env()
读环境变量 账户密码

2023-03-15 07:25 UTC, Norton-Lin commented on tools/quiz_voice_upload/quiz_voice_upload.py
> +import json
这个不急，等你批斗完代码再写233333

2023-03-15 07:31 UTC, FrogDar commented on tools/quiz_voice_upload/quiz_voice_upload.py
> +env = Env()
哦 后知后觉 你是要做“数据脱敏”是吧、、
才想起来这个事情
（原本想的就是账号密码的变量等于一个乱码x 23333）

2023-03-15 07:32 UTC, Norton-Lin commented on tools/quiz_voice_upload/quiz_voice_upload.py
> +env = Env()
乱码他咋登录23333

2023-03-19 16:29 UTC, FrogDar commented
话说 能用嘛
代码应该问题不大
你弄个到测试网站上试一试？

2023-03-21 05:53 UTC, FrogDar commented
@Norton-Lin 测试过嘛 测试过我就合并了？

2023-03-21 09:45 UTC, FrogDar commented
不对 傻逼了
这个就是直接改数据库 不要上传的

不过 upload文件如果坏掉也要修复一下的  我估计是测试服务器上面的 上传没配置好 正式服务器的可以用

2023-03-21 10:05 UTC, Norton-Lin commented
23333，那我那个upload还要不要

2023-03-22 16:01 UTC, FrogDar commented on tools/quiz_voice_upload/upload_file.py
这个东西为啥还在呀
以及上传的操作直接调用接口就行吧？
测试服的坏掉应该去修那个）

2023-03-22 16:03 UTC, Norton-Lin commented on tools/quiz_voice_upload/upload_file.py
噶了噶了

2023-03-22 16:06 UTC, merged