feat(article): some updates about likes of comments
e-dialect/hinghwa-dict-backend pull request #293
Opened 2023-03-23 13:00 UTC by lll123github

更新评论点赞功能
目前对于文章评论理想情况的测试还没有完全完善，主要的问题在于算数断言处格式的问题，还需要咨询apifox的群友

2023-03-23 13:39 UTC, FrogDar commented
> 更新评论点赞功能 目前对于文章评论理想情况的测试还没有完全完善，主要的问题在于算数断言处格式的问题，还需要咨询apifox的群友

那你加了 Apifox 的群吗？开始问了吗？

2023-03-23 13:40 UTC, FrogDar commented on hinghwa-dict-backend/article/migrations/0002_comment_like_users.py
> +    ]
```suggestion
    ]
    
```

2023-03-23 13:41 UTC, lll123github commented
开始问了，还没有答复

2023-03-23 13:43 UTC, lin594 commented on hinghwa-dict-backend/article/migrations/0002_comment_like_users.py
> +
```suggestion
# Generated by Django 3.1 on 2023-03-23 01:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="like_users",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                related_name="like_comments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="评论点赞用户",
            ),
        )
    ]

```

2023-03-23 13:45 UTC, lll123github commented
本地404通过了但是似乎自动化测试的没有通过我再修改一下

2023-03-23 13:52 UTC, FrogDar commented
不对  可能被你带歪了
真正没有格式化的应该不是 0002 那个文件而是其他的文件
你对全局格式化试一下

2023-03-23 13:53 UTC, lll123github commented
好的，我调整完测试之后试一下

2023-03-23 13:54 UTC, lin594 commented
以及你为什么不问一问你最爱的 chatgpt 呢？

![image](https://user-images.githubusercontent.com/20886330/227225561-add78c73-abe4-49cc-a6b7-5fa5cd808ce5.png)

2023-03-23 13:55 UTC, lll123github commented
它上次给了我一个虚构的函数，我深刻地意识到了它挺不可靠的/笑哭

2023-03-23 13:57 UTC, FrogDar commented
……

2023-03-23 14:36 UTC, FrogDar commented
…… 版本不对 修改了这么多没必要改的文件为啥还提交上来

2023-03-23 14:51 UTC, FrogDar commented on hinghwa-dict-backend/AudioCompare/InputFile.py
> -
这些其他的非必要改动可以去掉吗？

2023-03-23 14:52 UTC, FrogDar approved these changes

2023-03-23 14:53 UTC, lll123github commented
好像的确是black的版本问题？但是现在已经查不清楚了也……
原版本是19年的

2023-03-23 14:54 UTC, FrogDar requested changes

2023-03-23 14:54 UTC, lin594 commented on hinghwa-dict-backend/article/views.py
> +            raise BadRequestException("你还没有点赞过，不能取消文章评论点赞")
404错误

2023-03-23 14:54 UTC, lin594 commented on hinghwa-dict-backend/article/views.py
> +        return JsonResponse({}, status=200)
返回评论本体

2023-03-23 14:54 UTC, lin594 commented on hinghwa-dict-backend/article/views.py
> +        return JsonResponse({}, status=200)
msg: 删除成功

2023-03-23 14:54 UTC, lin594 commented on hinghwa-dict-backend/article/views.py
> +        comment.like_users.remove(user)
没有 save 的话真的能删除嘛？

2023-03-23 14:58 UTC, lll123github commented on hinghwa-dict-backend/article/views.py
> +            raise BadRequestException("你还没有点赞过，不能取消文章评论点赞")
404个人认为是找不到对应的评论之类的，按照前面的取消文章点赞的应该是？

2023-03-23 15:01 UTC, lll123github commented on hinghwa-dict-backend/article/views.py
> +        comment.like_users.remove(user)
有add

2023-03-23 15:12 UTC, lll123github commented on hinghwa-dict-backend/article/views.py
> +        return JsonResponse({}, status=200)
真的需要返回评论本体么？

2023-03-23 15:13 UTC, lll123github commented on hinghwa-dict-backend/article/views.py
> +        return JsonResponse({}, status=200)
因为看到文章点赞的时候没有返回文章本体就没有返回评论本体了

2023-03-23 15:15 UTC, lin594 commented on hinghwa-dict-backend/article/views.py
> +        return JsonResponse({}, status=200)
本体里应该有包括点赞信息吧？ 不对 你的dto 里是不是没有加这个信息

2023-03-23 15:16 UTC, lin594 commented on hinghwa-dict-backend/article/views.py
> +            raise BadRequestException("你还没有点赞过，不能取消文章评论点赞")
之前是 401 的话说明之前错了
点赞是一个对象，你在做删除一个不存在的东西 当然是 404

2023-03-23 15:17 UTC, lll123github commented on hinghwa-dict-backend/article/views.py
> +        return JsonResponse({}, status=200)
本体里面含有点赞信息，是整型数字

2023-03-23 15:20 UTC, lll123github commented on hinghwa-dict-backend/article/views.py
> +            raise BadRequestException("你还没有点赞过，不能取消文章评论点赞")
但是这样的话就会出现两个404，一个是找不到评论，一个是找不到该用户的点赞，确定这样么

2023-03-23 15:21 UTC, FrogDar commented on hinghwa-dict-backend/article/views.py
> +            raise BadRequestException("你还没有点赞过，不能取消文章评论点赞")
都是404 但是返回的文字不同

2023-03-23 15:23 UTC, lll123github commented on hinghwa-dict-backend/article/views.py
> +        return JsonResponse({}, status=200)
或者说返回一个点赞数？其它的感觉对于前端用处不大？

2023-03-23 15:23 UTC, lll123github commented on hinghwa-dict-backend/article/views.py
> +            raise BadRequestException("你还没有点赞过，不能取消文章评论点赞")
好的，但是这样的话得等到周末了，因为测试也需要大改

2023-03-23 15:27 UTC, lll123github commented on hinghwa-dict-backend/article/views.py
> +        return JsonResponse({}, status=200)
没有，对于目前代码里面的评论来说dto里面只有normal。实际上还有更高的all等级？

2023-03-23 15:29 UTC, FrogDar commented on hinghwa-dict-backend/article/views.py
> +        return JsonResponse({}, status=200)
> 本体里面含有点赞信息，是用户列表，dto含有列表计数

1. 要区分 normal 和 simple， 或者 normal 和 full 你自己定
2. 被别人调用+ 在此处输出 都是点赞数即可
3. full 或者什么的（反正就是返回本体那个） 也顶多是点赞数 + 最新5个点赞人即可

2023-03-23 15:31 UTC, lll123github commented on hinghwa-dict-backend/article/views.py
> +        return JsonResponse({}, status=200)
好的，我周末改一下

2023-03-24 08:59 UTC, lll123github commented
发现群友似乎直接忽略了我问的问题，可能可以使用自定义脚本解决会比较好一点？

2023-03-24 12:19 UTC, FrogDar commented
![image](https://user-images.githubusercontent.com/20886330/227519485-5cf10c56-a9d2-4a2f-b058-1228ee334311.png)

请使用这个功能关联 issue

2023-03-24 12:20 UTC, FrogDar commented
> 发现群友似乎直接忽略了我问的问题，可能可以使用自定义脚本解决会比较好一点？

要不然你继续问 要不然尝试办法解决 总之不要空耗时间

以及软著尽快完成

2023-04-04 13:56 UTC, lll123github commented
目前进度：由于是要最新的5个点赞，所以需要考虑数据库迁移的事情（正在进行）（就是中间表由自动生成改成自定义）
如果文章点赞也要这样的需求的话，也是需要做这样的事情
对于加减计算，在整理软著的过程中发现可以使用自定义脚本的方法完成。

2023-04-05 08:57 UTC, FrogDar commented
> 由于是要最新的5个点赞，所以需要考虑数据库迁移的事情（正在进行）
我说随便先返回前五个点赞，不代表着数据库不需要存全部的点赞……
只是类似于一个“DTO”  DTO 里只返回前五个罢了……

2023-04-05 10:00 UTC, lll123github commented
目前数据库是存着这样一个多对多关系，这个关系使用一个含有评论id和用户id字段的表。如果是要时间最近的话，就需要在这张表里面添加点赞时间这个字段，所以如果要返回最近的五个人的话，需要添加字段

2023-04-05 10:00 UTC, lll123github commented
那就先不按照时间返回五个人

2023-04-12 16:06 UTC, lll123github commented
还没有进行测试的修改

2023-04-14 00:17 UTC, lll123github commented
已经完成了，青蛙看看

2023-04-14 06:37 UTC, FrogDar commented
在 AT0405 的接口文档里不是说要制造 comment_all 的 dto 吗？怎么缩水成 comment_likes 了
我觉得 AT0405 和 AT0406 应该都是要去使用 comment_all 
（comment_all 某种程度上说 就是 comment_normal + 你现在写的 comment_likes 吧 ）

2023-04-14 06:42 UTC, FrogDar requested changes

2023-04-14 06:42 UTC, FrogDar commented on hinghwa-dict-backend/article/dto/comment_likes.py
> +    res_num = 5  # 指的是返回的点赞的用户个数
把这个变量作为参数传入函数呗，给他赋一个默认值5j就可以了

2023-04-14 06:42 UTC, FrogDar commented on hinghwa-dict-backend/article/dto/comment_likes.py
> +    comment_like_users = comment.like_users.filter(like_comments=comment)
comment.like_users 里难道还有不符合这个条件的情况吗？？？

2023-04-14 06:42 UTC, FrogDar commented on hinghwa-dict-backend/article/dto/comment_likes.py
> +def comment_likes(comment: Comment) -> dict:
为什么不是再加上 comment_normal 的内容行程 comment_all 呢？

2023-04-14 10:18 UTC, lll123github commented on hinghwa-dict-backend/article/dto/comment_likes.py
> +    comment_like_users = comment.like_users.filter(like_comments=comment)
你说得是，条件是可以不用了。

2023-04-14 10:18 UTC, lll123github commented on hinghwa-dict-backend/article/dto/comment_likes.py
> +def comment_likes(comment: Comment) -> dict:
我感觉是评论点赞的话返回comment_like就可以了，如果是获取评论内容的话返回comment_all。我修改一下

2023-04-17 09:52 UTC, lll123github commented on hinghwa-dict-backend/article/dto/comment_likes.py
> +def comment_likes(comment: Comment) -> dict:
还没有修改好

2023-04-17 09:54 UTC, lll123github commented
@FrogDar 自动化测试寄掉了，可能要更新pip？

2023-04-18 08:10 UTC, lll123github commented
close #283 #289

2023-04-18 08:28 UTC, FrogDar commented on hinghwa-dict-backend/article/dto/comment_all.py
> +        }
response 只要这个部分就好，不要再套一层 comment 了

2023-04-18 08:28 UTC, FrogDar commented on hinghwa-dict-backend/article/dto/comment_all.py
> +        }
comment 是你在 那个接口里添加的一层，而不是 dto 里添加的

2023-04-18 08:30 UTC, FrogDar commented on hinghwa-dict-backend/article/views.py
> +        return JsonResponse(comment_all(comment), status=200)
套的那层 comment 应该添加在这里
因为这里是叫 comment 其他地方万一换了一个名字呢？ 或者直接放在一个数组里呢？

2023-04-18 08:38 UTC, lll123github commented on hinghwa-dict-backend/article/views.py
> +        return JsonResponse(comment_all(comment), status=200)
好的

2023-04-19 02:37 UTC, FrogDar approved these changes

2023-04-19 02:40 UTC, merged