feat: create rewards and add some files
e-dialect/hinghwa-dict-backend pull request #307
Opened 2023-07-21 13:00 UTC by CapooL

2023-07-30 16:31 UTC, CapooL commented
奇怪），有个卡了我两天的测试问题本来想PR上来问问结果过了，在apifox上过了的结果这边CI没过

2023-07-31 04:55 UTC, FrogDar commented
> 奇怪），有个卡了我两天的测试问题本来想PR上来问问结果过了，在apifox上过了的结果这边CI没过

你好猛，一次能添加这么多内容

2023-07-31 05:01 UTC, FrogDar commented on hinghwa-dict-backend/rewards/models.py
> +class Products(models.Model):
为什么这个不一起拆分得了（）

2023-07-31 05:05 UTC, CapooL commented on hinghwa-dict-backend/rewards/models.py
> +class Products(models.Model):
这个我之前试过，按照现在的setting.py的设置，好像只能识别rewards目录下的model，拆分的话迁移不了）

2023-07-31 05:06 UTC, CapooL commented
> > 奇怪），有个卡了我两天的测试问题本来想PR上来问问结果过了，在apifox上过了的结果这边CI没过
> 
> 你好猛，一次能添加这么多内容

大头其实在测试文件）

2023-07-31 05:08 UTC, FrogDar commented on hinghwa-dict-backend/article/views.py
> +            action = "earn"
写这两行的目的在于什么）
如果是要方便全局的更改，那应该把这个设置为一个常量模块单独放在一个地方）

2023-07-31 05:09 UTC, FrogDar commented on hinghwa-dict-backend/article/views.py
> +        return JsonResponse({"transaction_id": transaction_id}, status=200)
只是返回id的话其实价值没有那么大）
（但是你已经辛苦地更改了Apifox那就算了

2023-07-31 06:44 UTC, FrogDar commented
![image](https://github.com/e-dialect/hinghwa-dict-backend/assets/20886330/11dfb13e-3d08-4b78-90b7-17f69b93e95e)

遇到这种情况，要在32行写反过来的，如果不足，直接ka掉，而不是长长的if-else
另，55行应该是个400之类的，不应该是500（正常的返回都不应该是5开头

2023-07-31 06:58 UTC, CapooL commented
看还有什么问题我一起改完再PR一版）

2023-07-31 08:14 UTC, FrogDar requested changes
全局替换 "title" -> "titles" 引发了很多不必要的修改
而你竟然选择把 Apifox 的相关测试用例也跟着改了、、、

2023-07-31 08:14 UTC, lin594 commented on hinghwa-dict-backend/quiz/views.py
> +import json
这个json最后在哪里用了吗）

2023-07-31 08:14 UTC, lin594 commented on hinghwa-dict-backend/quiz/views.py
> +            )
还是一样的问题，为啥要单列出来而不是直接写在153行那个里面呢

2023-07-31 08:14 UTC, lin594 commented on hinghwa-dict-backend/article/views.py
> +import json
去掉没用的引用）

2023-07-31 08:14 UTC, lin594 commented on hinghwa-dict-backend/website/views.py
> +                            "titles": article.title,
你是不是全局替换了…… 这种地方的 title 为什么要替换成titles？

2023-07-31 08:14 UTC, lin594 commented on hinghwa-dict-backend/word/pronunciation/views.py
> +        if ("orders" in request.GET) and request.GET["orders"] == "1":
order 也不应该替换成orders

2023-07-31 08:14 UTC, lin594 commented on hinghwa-dict-backend/word/word/views.py
> +            for it in body["orders"]:
不要乱替换诶、

2023-07-31 08:14 UTC, lin594 commented on hinghwa-dict-backend/word/word/dto/word_all.py
> +        {"id": article.id, "titles": article.title}
不要替换

2023-07-31 08:14 UTC, lin594 commented on hinghwa-dict-backend/word/word/dto/word_normal.py
> +        {"id": article.id, "titles": article.title}
不要替换

2023-07-31 08:28 UTC, FrogDar requested changes
再挖掘一批
改完这个之后还得鼓捣鼓捣站点管理的事情

2023-07-31 08:28 UTC, FrogDar commented on hinghwa-dict-backend/AudioCompare/Matcher.py
> +            # Do this using a pool of processes in orders
连注释都全局替换了、、

2023-07-31 08:28 UTC, FrogDar commented on hinghwa-dict-backend/rewards/orders/dto/orders_all.py
> +def orders_all(orders: Order):
这个可以改一下变量名，order
（用vscode+f2，他只会少关联不会多关联、、

2023-07-31 08:28 UTC, FrogDar commented on hinghwa-dict-backend/rewards/orders/views/Manage_all.py
> +        create_transaction(action=action, points=points, reason="兑换商品", user_id=user_id)
很不顺眼，还是合并一下吧）

2023-07-31 08:28 UTC, FrogDar commented on hinghwa-dict-backend/rewards/orders/views/Manage_all.py
> +        return JsonResponse({"id": orders.id}, status=200)
为什么不符返回order_all

2023-07-31 08:28 UTC, FrogDar commented on hinghwa-dict-backend/rewards/orders/views/Manage_all.py
> +        orders = Order.objects.filter(user=get_user_by_id(user_id))
TODO需要注明

2023-07-31 08:28 UTC, FrogDar commented on hinghwa-dict-backend/rewards/orders/views/Manage_single.py
> +        token = token_pass(request.headers, -1) or token_pass(request.headers, user_id)
我记得这个会自动触发异常了？
那更加应该在第一步就执行这个操作
避免恶意的查询请求

2023-07-31 08:28 UTC, FrogDar commented on hinghwa-dict-backend/rewards/orders/views/Manage_single.py
> +        token = token_pass(request.headers, -1) or token_pass(request.headers, user_id)
后面几个都是类似的改法

2023-07-31 08:28 UTC, FrogDar commented on hinghwa-dict-backend/rewards/products/dto/products_all.py
> +def products_all(products: Product) -> dict:
重命名一下 `product`

2023-07-31 08:28 UTC, FrogDar commented on hinghwa-dict-backend/rewards/products/views/Manage_single.py
> +        token = token_pass(request.headers, -1)
如果只检查，没有用到token，可以不写 `token = `

2023-07-31 08:28 UTC, FrogDar commented on hinghwa-dict-backend/website/notification/dto.py
> +        "titles": notification.verb,
不要titles

2023-07-31 08:28 UTC, FrogDar commented on hinghwa-dict-backend/website/notification/views.py
> +        title = body["titles"] if "titles" in body else None
不要titles

2023-07-31 08:28 UTC, FrogDar commented on hinghwa-dict-backend/website/views.py
> +    将id为order顺序排序objs,len(objs)<=len(orders)
不要orders

2023-07-31 08:28 UTC, FrogDar commented on hinghwa-dict-backend/website/views.py
> +                            "titles": article.title,
不要titles

2023-08-03 15:42 UTC, FrogDar commented on hinghwa-dict-backend/utils/Rewards_action.py
> +    elif 200 <= points_sum < 500:
python里这样子写是可以的嘛？

2023-08-03 15:42 UTC, FrogDar commented on hinghwa-dict-backend/rewards/orders/views/Manage_all.py
> +        orders = Order.objects.filter(user=get_user_by_id(user_id))
这个和Apifox不一致的地方还是弄点issue

2023-08-03 15:44 UTC, FrogDar commented on hinghwa-dict-backend/rewards/products/models/product.py
我不知道你又改了什么地方，但是如果会影响到迁移的话记得处理一下哦）

2023-08-03 15:44 UTC, FrogDar commented on hinghwa-dict-backend/rewards/titles/models/title.py
记得检查migration是否符合要求
如果符合的话直接点击finish即可

2023-08-05 14:43 UTC, FrogDar approved these changes
虽然还有很多小细节要处理，但是PR已经太大了，先合并一波吧

2023-08-05 14:44 UTC, merged