test: add test bash file
e-dialect/hinghwa-dict-backend pull request #309
Opened 2023-07-31 16:03 UTC by Topology2333

2023-07-31 16:38 UTC, FrogDar requested changes

2023-07-31 16:38 UTC, FrogDar commented on tools/README.md
> +### 说明：
为什么不喜欢加空行？Markdown这样子显示会有问题的

2023-07-31 16:38 UTC, lin594 commented on tools/README.md
> +### 说明：
```suggestion
### 后端测试小工具

```bash
python3 manage.py makemigrations
python3 manage.py migrate
DJANGO_SUPERUSER_PASSWORD=testtest123 python manage.py createsuperuser --username admin --email test@test.com --no-input
echo -e "from django.contrib.auth.models import User\nuser=User.objects.create_user('user_test','user_test@user_test.com','123456')\nuser.set_password('123456')\nuser.save()\nexit()" | python manage.py shell
echo -e "from django.contrib.auth.models import User\nuser=User.objects.create_user('user_test_old_password','user_test_old_password@user_test_old_password.com','12')\nuser.set_password('12')\nuser.save()\nexit()"| python manage.py shell
```

### 说明：
```

2023-07-31 16:39 UTC, FrogDar commented on tools/README.md
> +### 说明：
这个识别有小小的问题，还是靠你添加空行吧）

2023-08-01 02:49 UTC, closed without merging

2023-08-01 02:58 UTC, FrogDar commented
怎么还直接关闭PR了

2023-08-01 03:07 UTC, Topology2333 commented
> 怎么还直接关闭PR了

我重新创一个吧
以及：原文件第六行不就是没加空行🤣、、