feat(quiz): create quiz paper
e-dialect/hinghwa-dict-backend pull request #334
Opened 2023-10-19 09:27 UTC by CapooL

2023-10-19 13:21 UTC, Norton-Lin commented on hinghwa-dict-backend/quiz/paper/dto/paper_all.py
> +        # "record": [record_all(x) for x in paper.record.all()]
废弃代码？没用的话就砍了吧

2023-10-19 13:27 UTC, Norton-Lin commented on hinghwa-dict-backend/quiz/paper/view/manage_all.py
> +    @csrf_exempt
这个？有必要吗

2023-10-25 13:10 UTC, FrogDar requested changes

2023-10-25 13:10 UTC, lin594 commented on hinghwa-dict-backend/quiz/migrations/0004_auto_20231019_1116.py
文件改名，说明一下他真正做的事情

2023-10-25 13:10 UTC, lin594 commented on hinghwa-dict-backend/quiz/models.py
> +    quantity = models.IntegerField(blank=True, verbose_name="题目数量")
这个东西，没有必要单独存一下吧？我觉得直接从quizzes里导出就行
（类似于 有一个函数叫做 quantity 然后 return quizzes.count() 类似于这种感觉

2023-10-25 13:10 UTC, FrogDar commented on hinghwa-dict-backend/quiz/models.py
> +    )
这个东西感觉设计的不够详细，要不先删掉，下次再开一个PR来完成？

2023-10-27 19:01 UTC, FrogDar commented on hinghwa-dict-backend/quiz/models.py
> +    )
而且Record这个东西，我记得录音也叫这个名，是不是该换一个xxHistory之类的名字？不过这个后续再说了

2023-11-09 14:29 UTC, CapooL commented
这次应该都完成了

2023-11-13 08:23 UTC, FrogDar approved these changes

2023-11-13 08:24 UTC, merged