create Paper Record
e-dialect/hinghwa-dict-backend pull request #347
Opened 2023-11-30 13:07 UTC by CapooL

2023-12-01 11:59 UTC, FrogDar requested changes

2023-12-01 11:59 UTC, FrogDar commented on hinghwa-dict-backend/quiz/urls.py
>      path("/paper/<str:paper_id>", csrf_exempt(ManageSinglePaper.as_view())),
诶？你这样的路由的话会变成 `quizzes/paper/records` 诶，不过也行，但是 `paper` 应该复数吧

2023-12-01 11:59 UTC, FrogDar commented on hinghwa-dict-backend/word/migrations/0005_listadmin.py
这个为啥会突然删掉嘞？

2023-12-01 11:59 UTC, FrogDar commented on hinghwa-dict-backend/quiz/models.py
> +    examine = models.ForeignKey(
这个变量名怪怪的，要不要考虑换点 `contributor` 啊或者其他什么表示答卷人的词语

2023-12-01 11:59 UTC, FrogDar commented on hinghwa-dict-backend/quiz/paper/view/paper_record_all.py
> +        user = User.objects.filter(id=examine)
我记得token里面，可以直接提取到用户的吧，有一个 `token_user` 直接来获取，这里面还有做错误处理呢

2023-12-01 11:59 UTC, FrogDar commented on hinghwa-dict-backend/quiz/paper/view/paper_record_all.py
> +    # QZ0302 查询对应用户答题记录
答卷记录吧）这里面都还没开始弄答题记录的事情）

2023-12-06 13:39 UTC, CapooL commented on hinghwa-dict-backend/quiz/urls.py
>      path("/paper/<str:paper_id>", csrf_exempt(ManageSinglePaper.as_view())),
那是说这边路由直接换成quizzes/records？
那答卷和答题记录要分别用什么路由？

2023-12-06 13:40 UTC, CapooL commented on hinghwa-dict-backend/word/migrations/0005_listadmin.py
这个我是从老分支开始写的）那时候这个还没删掉，应该不会造成冲突

2023-12-06 15:10 UTC, CapooL commented on hinghwa-dict-backend/quiz/paper/view/paper_record_all.py
> +        user = User.objects.filter(id=examine)
就是说这个东西从用户发请求吗？

2023-12-07 08:34 UTC, FrogDar approved these changes

2023-12-07 08:35 UTC, FrogDar approved these changes

2023-12-07 08:36 UTC, merged