feat(user): add reset password by wechat
e-dialect/hinghwa-dict-backend pull request #351
Opened 2023-12-07 09:39 UTC by Norton-Lin

微信登录者，凭借自身token直接修改密码

2023-12-08 07:09 UTC, FrogDar requested changes
没有检测微信认证

2023-12-17 11:32 UTC, Norton-Lin commented
不好意思，忘了微信联动功能在这没法测试，我删一下

2023-12-17 11:32 UTC, Norton-Lin commented
不好意思，忘了微信联动功能在这没法测试，我删一下

2023-12-17 12:11 UTC, FrogDar commented on hinghwa-dict-backend/user/view/wechat.py
> +        password_validator(body["newpassword"])
其实正常来说应该这个得往前放比较好

2023-12-17 12:11 UTC, FrogDar approved these changes

2023-12-20 06:27 UTC, merged