feat(quiz): create QuizRecord
e-dialect/hinghwa-dict-backend pull request #352
Opened 2023-12-07 12:28 UTC by CapooL

2023-12-07 12:49 UTC, CapooL commented
赶着写就没删分支接着写了），merge那一步有点蠢了，冲突手动解决了

2023-12-08 07:15 UTC, FrogDar requested changes
QuizRecord 应该可以能独立使用？

2023-12-08 07:15 UTC, FrogDar commented on hinghwa-dict-backend/quiz/models.py
> +class QuizRecord(models.Model):
wu 你的 QuizRecord 要依附于 PaperRecord 吗？ 我本来以为是相关但独立的两个东西？

2023-12-08 07:15 UTC, FrogDar commented on hinghwa-dict-backend/quiz/models.py
> +    paper = models.ForeignKey(
这里应该是PaperRecord吧，而且是个可选项

2023-12-08 07:15 UTC, FrogDar commented on hinghwa-dict-backend/quiz/models.py
> +class QuizRecord(models.Model):
所以我设想中应该还有contributor、time之类的字段

2023-12-08 07:15 UTC, FrogDar commented on hinghwa-dict-backend/quiz/models.py
> +    paper = models.ForeignKey(
因为我认为不在卷子里也可能可以答题

2023-12-08 07:15 UTC, FrogDar commented on hinghwa-dict-backend/quiz/quiz_record/dto/quiz_record.py
> +        "paper": None if record.paper is None else paper_simple(record.paper),
总担心这里的返回会嵌套） 但是也都还行吧，大不了到时候再改

2023-12-22 09:10 UTC, FrogDar requested changes
一点小细节（

2023-12-22 09:10 UTC, FrogDar commented on hinghwa-dict-backend/quiz/migrations/0006_quizre_cord.py
文件命名错误

2023-12-22 09:10 UTC, FrogDar commented on hinghwa-dict-backend/quiz/models.py
> +        verbose_name="所在试卷",
所在答卷记录

2023-12-22 14:20 UTC, CapooL commented
> 一点小细节（

改完了

2023-12-22 16:49 UTC, FrogDar approved these changes

2023-12-22 16:49 UTC, merged