feat(word): creag tags Filed
e-dialect/hinghwa-dict-backend pull request #362
Opened 2024-03-28 02:31 UTC by CapooL

close #348

2024-03-28 09:53 UTC, lin594 requested changes
增删改查
删没影响
查已经有修改
增和改里面，对tag的处理似乎没有到位？

2024-03-28 09:53 UTC, lin594 commented on hinghwa-dict-backend/word/word/urls.py
> +    path("/search", csrf_exempt(searchWordsByTags)),
我以为直接用原本那个 /words 然后加一个选项就vans了？

2024-03-28 09:53 UTC, lin594 commented on hinghwa-dict-backend/word/word/views.py
> +        return JsonResponse({"msg": str(e)}, status=500)
不要写这种形式的try except，有中间件自动捕获这些异常

2024-03-28 14:31 UTC, lin594 requested changes
等一下，application里也应该同步增加tags吧？

2024-03-28 14:44 UTC, CapooL commented
> 等一下，application里也应该同步增加tags吧？

我看一下）

2024-04-15 01:53 UTC, lin594 approved these changes

2024-04-15 02:08 UTC, lin594 approved these changes

2024-04-15 02:09 UTC, merged